### ISSUE TITLE
Translations 

### ISSUE THREAD

**Issue by Phosphorus-M** [mainmatter/100-exercises-to-learn-rust#80]
Hi, I'm interested to see this project translated to Spanish.

Do you want this? I can offer me as a volunteer to translate it.

I'm doing this with the [official book of Rust](https://doc.rust-lang.org/book/) ([Translated version](https://book.rustlang-es.org)) and the Microsoft book, "[Rust for C#/.Net Devs](https://microsoft.github.io/rust-for-dotnet-devs/latest/)" ([Translated version](https://dotnet-book.rustlang-es.org)).

I know that the license that you are using allows me to do it, but I want a confirmation if you are interested to translate the book and if do you want to do it with our community [RustLangES](https://rustlang-es.org).

**Comment by bigfoodK** [comment]
I am also interested in translating this project into Korean.

How about using this tool [mdbook-i18n-helpers](https://github.com/google/mdbook-i18n-helpers) to support multiple languages?

**Comment by Phosphorus-M** [comment]
In the case of the C#/.Net book I do a custom fork of [mdbook](https://github.com/RustLangES/mdBook) using a old PR in the book and updating it.

**Comment by bigfoodK** [comment]
I have [translated the book into Korean](https://github.com/bigfoodK/100-exercises-to-learn-rust-kr/blob/main/book/translation/TRANSLATION.md), although I am not sure what method we will use and whether the main matter needs translation. Using the gettext-series tools to translate `.po` file was a great experience. I believe it will be easier to update the translation if the book changes because gettext supports [features related to merging with new versions](https://github.com/google/mdbook-i18n-helpers/blob/main/i18n-helpers/USAGE.md#updating-an-existing-translation).

**Comment by LukeMathWalker** [comment]
`gettext-series` would indeed be our preferred choice, using the same strategy employed by [Comprehensive Rust](https://github.com/google/comprehensive-rust).

**Comment by LukeMathWalker** [comment]
Coming back to this, we'd be happy to link to translations of the learning material, but we won't be hosting them in this repository.
