### ISSUE TITLE
Navigating into the folder each time you finish an exercise

### ISSUE THREAD

**Issue by NicholasDow** [mainmatter/100-exercises-to-learn-rust#85]
It's a little tedious to go into each folder when you complete an exercise. Is there a better way to do this? Is there a way to make a better way to do this?

**Comment by c-git** [comment]
I don't quite follow your workflow. There isn't really a need to go into each folder. When you run `wr` at the top level it gives you a link that you can just click on to open up the exercise in your IDE. I didn't test in Rust Rover but I'm pretty sure it would be abl to do it as well. I know it works in vscode which is what I did it in. Only reason I was having to go into the folders was because I wanted to run [bacon](https://github.com/Canop/bacon) (similar to cargo watch) on the exercise as I was going. Once you're done you again run `wr` at the top level so you only need to go into the folder if you want to use some other tool or something. I did eventually [modify `wr`](https://github.com/mainmatter/rust-workshop-runner/pull/11) to return only the path to the next exercise which I then feed into bacon so I never had to go into the folder again.

**Comment by NicholasDow** [comment]
I think the reason I am having this issue is because I use WSL for windows to run rust.
