### ISSUE TITLE
Questions about purpose of solutions for (04) traits - 14 (outro) 

### ISSUE THREAD

**Issue by jojohanhannesnes** [mainmatter/100-exercises-to-learn-rust#86]
Hi, I'm trying to understand something about the solutions code. Can someone explain what is the purpose of the piece of code below or why is it required? I'm confused because even when I remove it, the tests still pass. All I know is that it's related to fixing a warning about something called op_ref on the last assert_eq!.
```
impl std::ops::Add<&SaturatingU16> for SaturatingU16 {
    type Output = SaturatingU16;

    fn add(self, rhs: &SaturatingU16) -> Self::Output {
        self + *rhs
    }
}
```
Any insights would be much appreciated! Thanks in advance!

**Comment by c-git** [comment]
It doesn't have any effect on the warning for me. I get:

```
% cargo clippy --all-targets
warning: taken reference of right operand
  --> exercises/04_traits/14_outro/tests/integration.rs:15:16
   |
15 |     assert_eq!(a + &u16::MAX, SaturatingU16::from(u16::MAX));
   |                ^^^^---------
   |                    |
   |                    help: use the right value directly: `u16::MAX`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#op_ref
   = note: `#[warn(clippy::op_ref)]` on by default

warning: `outro_03` (test "integration") generated 1 warning
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.06s
```

My understanding is that this is related to the & used in the last assert no to the code you are asking about.

Regarding your question:
The purpose is for adding a reference to an owned type. I think the compiler automatically derefernces the last case to make it work without it, and that's why there is a warning but consider the following test where it does fail if you remove it.

```rust
#[test]
fn test_saturating_u16() {
    let a: SaturatingU16 = (&10u8).into();
    let b: SaturatingU16 = 5u8.into();
    let c: SaturatingU16 = u16::MAX.into();
    let d: SaturatingU16 = (&1u16).into();
    let e = &c;

    assert_eq!(a + b, SaturatingU16::from(15u16));
    assert_eq!(a + c, SaturatingU16::from(u16::MAX));
    assert_eq!(a + d, SaturatingU16::from(11u16));
    assert_eq!(a + a, 20u16);
    assert_eq!(a + 5u16, 15u16);
    assert_eq!(a + e, SaturatingU16::from(u16::MAX));
}
```

**Comment by jojohanhannesnes** [comment]
So if I understand correctly, the `impl` block is specifically for enabling addition operations between any type `T` and a reference to `T`, assuming in this case it's `SaturatingU16`. In the future, if I want to ensure that I can perform addition operations on my own custom types or structs, I can use a similar signature like this:

```rust
impl Add<&T> for T {
    ...
}
```

Regarding the last assertion, I assume that sometimes, when the value is direct, the compiler will optimize it. But if we store it in a variable, the compiler won't try to make assumptions.

Thanks for the explanation @c-git , it really helped!

**Comment by c-git** [comment]
> Regarding the last assertion, I assume that sometimes, when the value is direct, the compiler will optimize it. But if we store it in a variable, the compiler won't try to make assumptions.

My understanding (didn't have time to look it up) is if the compiler can either add the reference or remove it to make the code work it will. But by putting it in a variable that's no longer a change it can make because it would mean a hidden allocation because it's not just to remove an '&' from the code anymore. It would require a clone.
