### ISSUE TITLE
Questions about (05) ticket_v2 - (13) try_from

### ISSUE THREAD

**Issue by jojohanhannesnes** [mainmatter/100-exercises-to-learn-rust#91]
In this task, I've completed the part where I add both features to the `Status` enum. But after watching (https://www.youtube.com/watch?v=b0bgAYJDhhQ) i'm tempted to try out the code below:

```rust
impl TryFrom<Into<String>> for Status {
    type Error = ParseStatusError;

    fn try_from(value: impl Into<String>) -> Result<Self, Self::Error> {
        let value: String = value.into();
        match value.to_lowercase().as_str() {
            "todo" => Ok(Status::ToDo),
            "inprogress" => Ok(Status::InProgress),
            "done" => Ok(Status::Done),
            _ => unimplemented!(),
        }
    }
}
```
I ran into problems like "`Into` can't become an object" and some others.

I also tried `pub trait MyTrait: Into<String> + Sized {}` (because https://doc.rust-lang.org/std/convert/trait.TryFrom.html requires a subtrait Sized). But it looks like doing it the way I wanted is not possible.

Now i'm wondering, I'm not sure if it's just my approach that's wrong or it's just impossible. 
Any insights and suggestions would be greatly appreciated.

**Comment by c-git** [comment]
Below are my personal thoughts.

> I ran into problems like "Into can't become an object" and some others.

I've never gotten an error like that, do you have the code that produces the error?

> ... `pub trait MyTrait: Into<String> + Sized {}`

I don't think that would be needed because Sized is implied to be required unless you opt out. It is covered during this course (but I don't remember where and don't have the time to look it up at the moment).

> ` _ => unimplemented!(),`

1. I think the point of using `TryFrom` instead of `From` is so that the function can be fallible and have a way to handle errors without panicking. So panicking here doesn't quite seem appropriate. 
2. I think the community moved towards `todo!()` instead of `unimplemented!()` because it better shows intention. For example right not I'm not sure if you just haven't finished why you stuck that in there or if you don't plan to handle the other cases.

> Now i'm wondering, I'm not sure if it's just my approach that's wrong or it's just impossible.
Any insights and suggestions would be greatly appreciated.

For the most part your approach looks correct but I don't know what concrete problems you are getting so I can't actually give useful help. IMO it might be better to give us up to where you reach along with the problem you're having.
